schedules:
- cron: '0 2 * * 0'
  displayName: 'Run at 2:00 AM every Sunday (UTC)'
  always: true
  branches:
    include:
    - develop

trigger:
  - develop
  - main    
  - releases/*  
  
pool:
  vmImage: ubuntu-latest

steps:
# Build mock-register
- task: Docker@2
  displayName: Build mock-register image
  inputs:
    command: build 
    Dockerfile: ./Source/Dockerfile
    buildContext: ./Source
    repository: mock-register
    tags: latest

# Build mock-register-unit-tests
- task: Docker@2
  displayName: Build mock-register-unit-tests image
  inputs:
    command: build 
    Dockerfile: ./Source/Dockerfile
    buildContext: ./Source
    repository: mock-register-unit-tests
    tags: latest
    arguments: --target unit-tests

# Build mock-register-integration-tests
- task: Docker@2
  displayName: Build mock-register-integration-tests image
  inputs:
    command: build 
    Dockerfile: ./Source/Dockerfile
    buildContext: ./Source
    repository: mock-register-integration-tests
    tags: latest
    arguments: --target integration-tests

# List docker images
- task: Docker@2
  displayName: List Docker images
  condition: always() 
  inputs:
    command: images

# Run unit tests
- script: |
      docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.UnitTests.yml up --abort-on-container-exit --exit-code-from mock-register-unit-tests
  displayName: 'Unit Tests - Up'  
  condition: always()

# Remove unit tests
- script: |
    docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.UnitTests.yml down 
  displayName: 'Unit Tests - Down' 
  condition: always() 

# Login to Shared ACR
- task: Docker@2
  displayName: Login to Shared ACR
  inputs:
    command: login    
    containerRegistry: $(SpSharedAcr)

#****************************************************************************************************************
# Run integration tests
#****************************************************************************************************************
- script: |
    docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.IntegrationTests.yml up --abort-on-container-exit --exit-code-from mock-register-integration-tests
  displayName: 'Integration Tests - Up'  
  condition: always()

# Remove integration tests
- script: |
        docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.IntegrationTests.yml down 
  displayName: 'Integration Tests - Down' 
  condition: always()
    
# Run trx formatter to output .MD and .CSV
- script: |
    docker run \
      -v=$(Build.SourcesDirectory)/Source/_temp/mock-register-integration-tests/testresults/results.trx:/app/results.trx:ro \
      -v=$(Build.SourcesDirectory)/Source/_temp/mock-register-integration-tests/testresults/formatted/:/app/out/:rw \
      $(SharedAcrBaseUrl).azurecr.io/trx-formatter -i results.trx -t "MR" --outputprefix "MR" -o out/
  displayName: 'Run trx-formatter'  
  condition: always()
  env:
    TEST_FILTER: "Category!=CTSONLY"    

# Publish mock-register integration tests results
- publish: Source/_temp/mock-register-integration-tests/testresults
  displayName: Publish MockRegister Integration tests
  condition: always()
  artifact: Mock-Register - Integration tests 
  
- task: PublishTestResults@2
  displayName: 'Surface Integration Test TRX results to devops'
  condition: succeededOrFailed()
  inputs:
    testRunTitle: "integration-tests" # Optional
    testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/results.trx' 
    publishRunAttachments: true # Optional

#****************************************************************************************************************    
# Run integration tests For CTS Only tests
#****************************************************************************************************************
- script: |
        docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.IntegrationTests.yml up --abort-on-container-exit --exit-code-from mock-register-integration-tests
  displayName: 'Integration Tests Tests For CTS Only - Up'  
  condition: always()
  env:
    TEST_FILTER: "Category=CTSONLY"    
    CtsSettings__AzureAd__TokenEndpointUrl: '$(CtsSettings__AzureAd__TokenEndpointUrl)'
    CtsSettings__AzureAd__ClientId: '$(CtsSettings__AzureAd__ClientId)'
    CtsSettings__AzureAd__ClientSecret: '$(CtsSettings__AzureAd__ClientSecret)'
    CtsSettings__AzureAd__Scope: '$(CtsSettings__AzureAd__Scope)'
    CtsSettings__AzureAd__GrantType: '$(CtsSettings__AzureAd__GrantType)'
    CtsSettings__AzureAd__UnauthorisedClientId: '$(CtsSettings__AzureAd__UnauthorisedClientId)'
    CtsSettings__AzureAd__UnauthorisedClientSecret: '$(CtsSettings__AzureAd__UnauthorisedClientSecret)'
    IdentityProvider_Downstream_BaseUrl: '$(IdentityProvider_Downstream_BaseUrl)'
    Authorization__Issuer: '$(Authorization__Issuer)'
    Authorization__ClientId: '$(Authorization__ClientId)'
    Authorization__Scope: '$(Authorization__Scope)'
    BasePathExpression: '$(BasePathExpression)'
    BasePath: '$(BasePath)'
    PublicHostName: '$(CtsPublicHostNameUrl)'
    SecureHostName: '$(CtsSecureHostNameUrl)'
    Certificate__CertThumbprintNameHttpHeaderName: '$(CtsSettings__CertThumbprintNameHttpHeaderName)'
    Certificate__CertCommonNameHttpHeaderName: '$(CtsSettings_CertCommonNameHttpHeaderName)'

# Run trx formatter to output .MD and .CSV
- script: |
    docker run \
      -v=$(Build.SourcesDirectory)/Source/_temp/mock-register-integration-tests/testresults/results.trx:/app/results.trx:ro \
      -v=$(Build.SourcesDirectory)/Source/_temp/mock-register-integration-tests/testresults/formatted/:/app/out/:rw \
      $(SharedAcrBaseUrl).azurecr.io/trx-formatter -i results.trx -t "MR-CTS" --outputprefix "MR-CTS" -o out/
  displayName: 'Run trx-formatter'  
  condition: always()   

# Remove integration tests For CTS Only tests
- script: |
    docker compose --file $(Build.SourcesDirectory)/Source/docker-compose.IntegrationTests.yml down 
  displayName: 'Integration Tests For CTS Only - Down' 
  condition: always()

# Publish mock-register integration tests results
- publish: Source/_temp/mock-register-integration-tests/testresults
  displayName: Publish MockRegister CTS Integration tests
  condition: always()
  artifact: Mock-Register - CTS Integration tests 
  
- task: PublishTestResults@2
  displayName: 'Surface Integration CTS Test TRX results to devops'
  condition: succeededOrFailed()
  inputs:
    testRunTitle: "integration-tests-CTS-Only" # Optional
    testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/results.trx' 
    publishRunAttachments: true # Optional
#****************************************************************************************************************

# Save docker image to TAR so it can be published
- task: Docker@2
  displayName: Save MockRegister image to TAR
  inputs:
    repository: mock-register
    command: save
    arguments: --output $(build.artifactstagingdirectory)/mock-register.image.tar mock-register
    addPipelineData: false

# Publish docker image
- task: PublishPipelineArtifact@1
  displayName: Publish container images  
  # condition: always()
  inputs:
    path: $(build.artifactstagingdirectory)
    artifact: Container Images

# FIXME - MJS - See dockercompose, volume no longer mapped as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops register from starting because of different user
# # Publish mock-register logs
# - publish: Source/_temp/mock-register/tmp
#   displayName: Publish MockRegister logs
#   condition: always()
#   artifact: Mock-Register - Logs

# Publish mock-register unit tests results
- publish: Source/_temp/mock-register-unit-tests/testresults
  displayName: Publish unit tests
  condition: always()
  artifact: Mock-Register - Unit tests

- task: UseDotNet@2
  displayName: 'Use .NET 8 sdk'
  condition: always()
  inputs:
    packageType: sdk
    version: '8.0.x'
    performMultiLevelLookup: true

- task: CmdLine@2
  displayName: 'Restore dotnet tooling'
  condition: always()
  inputs:
    script: 'dotnet tool restore'
    
- script: |
    cd Source/CDR.Register.Repository 
    dotnet ef migrations bundle --context RegisterDatabaseContext --verbose --self-contained
    ls
  displayName: 'Run EF Migrations bundle'
  condition: always()

- publish: Source/CDR.Register.Repository/efbundle
  displayName: Publish EF Migration bundle
  condition: always()
  artifact: Database Migration Scripts 

- task: Bash@3
  displayName: 'Tag and push Mock Register image with Source Branch Name for any successful builds.'
  condition: succeeded()
  inputs:
    targetType: inline
    script: |
      echo Tagging mock-register with Source Branch Name: $(Build.SourceBranchName)
      docker tag mock-register $(SharedAcrBaseUrl).azurecr.io/mock-register:$(Build.SourceBranchName)

      echo Pushing all tags to $(SharedAcrBaseUrl).azurecr.io/mock-register
      docker image push --all-tags $(SharedAcrBaseUrl).azurecr.io/mock-register

- task: Bash@3
  displayName: 'Tag and Push Mock Register images for develop, main and release branches.'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')))
  inputs:
    targetType: inline
    script: |
      echo Tagging mock-register with latest tag
      docker tag mock-register $(SharedAcrBaseUrl).azurecr.io/mock-register:latest

      echo Tagging mock-register with Source Branch Name-latest: $(Build.SourceBranchName)-latest
      docker tag mock-register $(SharedAcrBaseUrl).azurecr.io/mock-register:$(Build.SourceBranchName)-latest

      if [ -n "$(ObligationDate)" ]; then
        echo Tagging mock-register with obligation date: $(Build.SourceBranchName)-$(ObligationDate)
        docker tag mock-register $(SharedAcrBaseUrl).azurecr.io/mock-register:$(Build.SourceBranchName)-$(ObligationDate)
      fi

      echo Tagging mock-register with build id: $(Build.BuildId)
      docker tag mock-register $(SharedAcrBaseUrl).azurecr.io/mock-register:$(Build.BuildId)

      echo Pushing all tags to $(SharedAcrBaseUrl).azurecr.io/mock-register
      docker image push --all-tags $(SharedAcrBaseUrl).azurecr.io/mock-register