schedules:
- cron: "0 14 * * *"
  displayName: Daily Dependabot Run
  branches:
    include:
    - refs/heads/develop
  always: true

jobs:
- job: dependabot
  displayName: Dependabot
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: CmdLine@2
    displayName: clone dependabot repo
    inputs:
      script: |
        git clone https://github.com/dependabot/dependabot-script.git
    
  - task: CmdLine@2
    displayName: pull dependabot-core Docker image
    inputs:
      script: docker pull dependabot/dependabot-core

  - task: CmdLine@2
    displayName: install dependencies
    inputs:
      script: |
        cd dependabot-script
        docker run -v "$(pwd):/home/dependabot/dependabot-script" \
                  --user $(id -u):$(id -g) \
                  -w /home/dependabot/dependabot-script dependabot/dependabot-core bundle install \
                  -j 3 \
                  --path vendor

  - task: CmdLine@2
    displayName: remove new line chars
    inputs:
      script: sed -i 's/\r//g' .azuredevops/pipelines/scripts/dependabot-devops.sh

  - task: Bash@3
    displayName: run dependabot nuget
    inputs:
      filePath: '.azuredevops/pipelines/scripts/dependabot-devops.sh'
    env:
      PACKAGE_MANAGER: 'nuget'
      SOURCE_CODE_PATH: '/Source'
      PERSONAL_ACCESS_TOKEN: $(PERSONAL_ACCESS_TOKEN)

  - task: Bash@3
    displayName: run dependabot docker
    inputs:
      filePath: '.azuredevops/pipelines/scripts/dependabot-devops.sh'
    env:
      PACKAGE_MANAGER: 'docker'
      SOURCE_CODE_PATH: '/Source'
      PERSONAL_ACCESS_TOKEN: $(PERSONAL_ACCESS_TOKEN)